In [2]:
import numpy as np

In [4]:
data = [[1, 2, 3], [2, 3, 4]]
arr = np.array(data)
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [5]:
arr.shape

(2, 3)

In [8]:
arr.shape[0]

2

In [10]:
x = np.array([[7, 8, 9], [10, 11, 12]])
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [11]:
x[1:]

array([[10, 11, 12]])

In [12]:
x[:, 1:]

array([[ 8,  9],
       [11, 12]])

In [34]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y.shape

(3, 3)

In [36]:
y[1, :2]

array([4, 5])

In [31]:
y[1:2, :2]

array([[4, 5]])

In [19]:
y[0, 1]

2

In [37]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [38]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [42]:
arr[[1, 5, 7, 2]][[0, 3, 1, 2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [43]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])